apiVersion: apps/v1
kind: Deployment
metadata:
  name: saikumar01
spec:
  selector:
    matchLabels:
      app: saikumar01-pod
  template:
    metadata:
      labels:
        app: saikumar01-pod
    spec:
      containers:
      - name: myapp
        image: cloudnativeacr01.azurecr.io/saikumar01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
